# Generated by Django 5.1.3 on 2025-05-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
