# Generated by Django 5.1.3 on 2025-05-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_roomtype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_type_images/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_images', to='booking.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Изображение типа номера',
                'verbose_name_plural': 'Изображения типов номеров',
            },
        ),
    ]
